services:
  spotify-history-tracker:
    build: .
    image: ${IMAGE_NAME}
    container_name: spotify-history-tracker
    env_file:
      - ./.env
    environment:
      - OUTPUT_DIR=/app/output
    volumes:
      - ${OUTPUT_HOST_DIR}:/app/output
      - ./.cache:/app/.cache
