services:
  spotify-history-tracker:
    image: ${IMAGE_NAME}
    container_name: spotify-history-tracker
    env_file:
      - ./.env
    environment:
      - OUTPUT_DIR=/app/output
    ports:
      - "${SPOTIFY_CALLBACK_PORT:-8888}:${SPOTIFY_CALLBACK_PORT:-8888}"
    volumes:
      - ${OUTPUT_HOST_DIR}:/app/output
      - ./.cache:/app/.cache
