version: "3.8"

services:
  spotify-history-tracker:
    build: .
    container_name: spotify-history-tracker
    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - OUTPUT_DIR=/app/output
    volumes:
      - ./output:/app/output
      - ./.cache:/app/.cache
